# <en><center>Numpy</center></en>

## Arrays

In [2]:
import numpy as np

In [1]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Create an array easily using the arange method.
- The arange method includes the first argument and excludes the last argument.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Linspace creates equally spaced points within the range of its arguments.

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Create an identity matrix

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random numbers from normal distribution

In [3]:
np.random.rand(5)

array([0.74721605, 0.1568564 , 0.41029463, 0.91499141, 0.44526581])

In [4]:
np.random.rand(5,5)

array([[0.14792343, 0.4826661 , 0.48174503, 0.70894866, 0.51809782],
       [0.69525185, 0.21305663, 0.37844927, 0.71671664, 0.21363081],
       [0.35559307, 0.14801723, 0.9960647 , 0.49352544, 0.89661803],
       [0.32214455, 0.96994463, 0.58421164, 0.87713089, 0.77847471],
       [0.8998978 , 0.51052172, 0.25596117, 0.82820607, 0.51510065]])

Gaussian Standard Normal distribution

In [5]:
np.random.randn(2)

array([ 1.58874009, -1.00180978])

In [6]:
np.random.randn(4,4)

array([[-0.03038114, -0.33917922,  0.94214225, -1.00648618],
       [-1.36141237, -1.06591034, -1.31592822, -0.17425413],
       [-0.03213984, -1.25970099, -2.05875881,  0.12218077],
       [-0.00789686,  0.89881514, -0.28021373, -1.08659917]])

In [7]:
np.random.randint(1,100,10)

array([76, 12,  1,  1, 11,  7, 75,  3, 52, 92])

In [8]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
ranarr = np.random.randint(0,50,10)
ranarr

array([42,  3,  6, 21, 12, 49, 45, 39, 38, 37])

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
ranarr.max()

49

In [13]:
ranarr.min()

3

Use argmax or argmin to find the index location of the max and min values in an array.