# <en><center>Numpy</center></en>

## Arrays

In [1]:
import numpy as np

In [1]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Create an array easily using the arange method.
- The arange method includes the first argument and excludes the last argument.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Linspace creates equally spaced points within the range of its arguments.

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Create an identity matrix

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random numbers from normal distribution

In [3]:
np.random.rand(5)

array([0.74721605, 0.1568564 , 0.41029463, 0.91499141, 0.44526581])

In [4]:
np.random.rand(5,5)

array([[0.14792343, 0.4826661 , 0.48174503, 0.70894866, 0.51809782],
       [0.69525185, 0.21305663, 0.37844927, 0.71671664, 0.21363081],
       [0.35559307, 0.14801723, 0.9960647 , 0.49352544, 0.89661803],
       [0.32214455, 0.96994463, 0.58421164, 0.87713089, 0.77847471],
       [0.8998978 , 0.51052172, 0.25596117, 0.82820607, 0.51510065]])

Gaussian Standard Normal distribution

In [5]:
np.random.randn(2)

array([ 1.58874009, -1.00180978])

In [6]:
np.random.randn(4,4)

array([[-0.03038114, -0.33917922,  0.94214225, -1.00648618],
       [-1.36141237, -1.06591034, -1.31592822, -0.17425413],
       [-0.03213984, -1.25970099, -2.05875881,  0.12218077],
       [-0.00789686,  0.89881514, -0.28021373, -1.08659917]])

In [7]:
np.random.randint(1,100,10)

array([76, 12,  1,  1, 11,  7, 75,  3, 52, 92])

In [8]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
ranarr = np.random.randint(0,50,10)
ranarr

array([42,  3,  6, 21, 12, 49, 45, 39, 38, 37])

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
ranarr.max()

49

In [13]:
ranarr.min()

3

Use argmax or argmin to find the index location of the max and min values in an array.

In [14]:
ranarr.argmax()

5

In [15]:
ranarr.argmin()

1

In [17]:
arr.shape

(25,)

In [20]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.shape

(5, 5)

In [22]:
arr.dtype

dtype('int32')

In [23]:
from numpy.random import randint

In [24]:
randint(2,10)

5

## Numpy Indexing and Selection

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[8]

8

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [34]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [35]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

Numpy Arrays have the ability to broadcast

In [41]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice_of_arr = arr[0:6]

In [48]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [49]:
slice_of_arr[:] =  100

In [50]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

You deliberately need to make a copy to prevent broadcasting in numpy

In [51]:
arr_copy = arr.copy()

In [52]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [53]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [56]:
arr_copy[:] =  100

In [57]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [55]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [59]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Double bracket notation for selection

In [60]:
arr_2d[0]

array([ 5, 10, 15])

In [61]:
arr_2d[1][1]

25

In [62]:
arr_2d[2][1]

40

In [63]:
arr_2d[0][2]

15

Comma notation for selection

In [65]:
arr_2d[1,2]

30

In [66]:
arr_2d[1][2]

30

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [74]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Gives an output of array consisting of booleans for each value

In [77]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [80]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [81]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr<3]

array([1, 2])

In [3]:
arr_2d = np.arange(50).reshape(5,10)

Practice

In [4]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Grab 13 and 14

In [7]:
arr_2d[1,3:5]

array([13, 14])

Grab 36,37,38

In [9]:
arr_2d[3,6:9]

array([36, 37, 38])

Grab 20 and 21

In [10]:
arr_2d[0:2,2]

array([ 2, 12])

In [11]:
arr_2d[0:5,8]

array([ 8, 18, 28, 38, 48])

In [12]:
arr_2d[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[]

Grab 36 to 39

In [15]:
arr_2d[3,6:8]

array([36, 37])

Grab 21 and 22

In [16]:
arr_2d[2,1:3]

array([21, 22])

## Numpy Operations

In [18]:
import numpy as np

In [19]:
arr = np.arange(0,11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [24]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [25]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [26]:
arr / arr

C:\Users\pyria\AppData\Local\Temp\ipykernel_10892\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
1 / arr

C:\Users\pyria\AppData\Local\Temp\ipykernel_10892\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [28]:
pow(arr, 2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [29]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [30]:
np.max(arr)

10

In [31]:
arr.argmax()

10

In [32]:
np.min(arr)

0

In [33]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [34]:
arr2 = np.arange(50,101)

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [35]:
import numpy as np

#### Create an array of 10 zeros 

In [38]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

In [40]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [41]:
arr_of_fives = np.ones(10)*5
arr_of_fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

In [43]:
array_10_to_50 = np.arange(10,51)
array_10_to_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [44]:
arrayevens_10_to_50 = np.arange(10,51,2)
arrayevens_10_to_50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [46]:
for i in array_10_to_50:
    if i % 2 == 0:
        print(i)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [49]:
matrix3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
matrix3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [50]:
eyes = np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [54]:
np.random.rand(1)

array([0.48114895])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [55]:
np.random.randn(25)

array([ 1.82638407,  0.05349585,  1.45117082,  3.08788645, -1.36311937,
       -0.75692213,  0.01955364, -1.50152832, -0.23383333, -0.70561297,
       -0.28521234, -0.05433774, -1.18062531, -1.29859766,  2.19165357,
       -0.71242648, -0.03084297,  0.34239974,  0.53687092, -0.91421372,
       -0.58401975,  0.2069668 , -0.70793773, -1.02681937,  0.97618815])

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

In [66]:
array100 = np.arange(1,101).reshape(10,10)/100
array100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [67]:
linarray = np.linspace(0,1,20)
linarray

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [75]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [95]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [97]:
mat[3,4]

20

In [99]:
mat[0:3,1]

array([ 2,  7, 12])

In [100]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
mat[4]

array([21, 22, 23, 24, 25])

In [104]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [106]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [112]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [114]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])